dist: trusty
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
language: node_js java
node_js:
  - "4"
jdk:
  - oraclejdk8
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
  matrix:
    - NG_SCRIPT=lint
    - NG_SCRIPT=single-test
    - NG_SCRIPT=style-lint

before_install:
  - if [[ "$TRAVIS_BRANCH" =~ "front-" ]]; then IS_FRONT=1; else IS_FRONT=0; fi
  - if [[ "$TRAVIS_BRANCH" =~ "back-" ]]; then IS_BACK=1; else IS_BACK=0; fi
  - if [[ "$NG_SCRIPT" && "$IS_BACK" != 1 ]]; then IS_NG=1; fi
  - if [[ "$NG_SCRIPT" && "$IS_FRONT" != 1 ]]; then IS_SB=1; fi
  - if [[ "$IS_SB" ]]; then cd back; fi
  - if [[ "$IS_NG" ]]; then echo "Starting front tests..."; fi
  - if [[ "$IS_NG" ]]; then cd front; fi
  - if [[ "$IS_NG" ]]; then npm install -g npm; fi
  - if [[ "$IS_NG" ]]; then npm install -g angular-cli; fi
  - if [[ "$IS_NG" ]]; then export CHROME_BIN=chromium-browser; fi
  - if [[ "$IS_NG" ]]; then echo "--no-sandbox" > ~/.config/chromium-flags.conf; fi
  - if [[ "$IS_NG" ]]; then npm config set spin false; fi
  - if [[ "$IS_NG" ]]; then npm config set progress false; fi

install:
  - if [[ "$IS_NG" ]]; then npm install --no-optional; fi

before_script:
  - if [[ "$IS_NG" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$IS_NG" ]]; then sh -e /etc/init.d/xvfb start; fi
  - sleep 3;

script:
  - if [[ "$NG_SCRIPT" && "$IS_NG" ]]; then npm run $NG_SCRIPT; fi
  - if [[ "$IS_SB" ]]; then mvn test; fi
