package org.lendi.umtapo.marc.transformer;

import org.marc4j.marc.Record;

/**
 * Transform a Marc specific format record to another object.
 */
public interface RecordTransformer <T> {
    /**
     * Process the transformation of the set record.
     *
     * @return Object generated by transformation, null if no record is previously set.
     */
    T transform(Record record);
}
